# Generated by Django 4.2.4 on 2023-08-29 18:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_sem2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='kick_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 21, 17, 16, 853732)),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('public_date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('public', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_sem2.author')),
            ],
        ),
    ]
